Clean up error aggregation and reporting in distributed TF.
In distributed TF, a failure in one executor thread can cause all the other executors threads and workers to stop their execution and report errors.
The previous error aggregation and reporting scheme frequently results in confusing error messages displayed to the end user. The error message for the root failure may get buried in a long error message or dropped entirely. In this CL, We mark all the derived errors with a special marker ('_Derived_'). The master node aggregates the errors and only forward nonderived errors to the end user, so that the end user only sees the error message related to the root cause of the failure.

Below is the error message for a simple distributed TF with two worker nodes before and after the change that shows how the error message seen by the user is simplified.

Before the CL:
=============

InvalidArgumentError: Combined status information from 3 operations:

Status code: Cancelled [1x]
  Cancelled
  Additional GRPC error information:
  {"created":"@1554489988.947430580","description":"Error received from peer ipv6:[::1]:9998","file":"third_party/grpc/src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"Cancelled","grpc_status":1} [1x]
Status code: Invalid argument [2x]
  Integer division by zero
         [[node add_b (defined at /experimental/users/jingdong/tf_examples/test_partition_worker.py:23) ]] [1x]
  Integer division by zero
         [[node add_b (defined at /experimental/users/jingdong/tf_examples/test_partition_worker.py:23) ]]
  Additional GRPC error information:
  {"created":"@1554489988.946134383","description":"Error received from peer ipv6:[::1]:9999","file":"third_party/grpc/src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"Integer division by zero\n\t [[node add_b (defined at /experimental/users/jingdong/tf_examples/test_partition_worker.py:23) ]]","grpc_status":3}
         [[add_b_S9]]
  Additional GRPC error information:
  {"created":"@1554489988.950078325","description":"Error received from peer ipv6:[::1]:9998","file":"third_party/grpc/src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"Integer division by zero\n\t [[node add_b (defined at /experimental/users/jingdong/tf_examples/test_partition_worker.py:23) ]]\nAdditional GRPC error information:\n{"created":"@1554489988.946134383","description":"Error received from peer ipv6:[::1]:9999","file":"third_party/grpc/src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"Integer division by zero\n\t [[node add_b (defined at /experimental/users/jingdong/tf_examples/test_partition_worker.py:23) ]]","grpc_status":3}\n\t [[add_b_S9]]","grpc_status":3}
         [[add_c_S11]] [1x]
(0 successful operations.)

Errors may have originated from an input operation.
Input Source operations connected to node add_b:
 add_a (defined at /experimental/users/jingdong/tf_examples/test_partition_worker.py:19)
 zeros (defined at /experimental/users/jingdong/tf_examples/test_partition_worker.py:22)

Input Source operations connected to node add_b:
 add_a (defined at /experimental/users/jingdong/tf_examples/test_partition_worker.py:19)
 zeros (defined at /experimental/users/jingdong/tf_examples/test_partition_worker.py:22)

After the CL:
=============

InvalidArgumentError:
=====================
InvalidArgumentError: From /job:worker/replica:0/task:2:
Status Group Summary: 1 nonderived error status, 0 derived error status, 0 success status
  (0) Invalid argument: Integer division by zero
         [[node add_b (defined at /experimental/users/jingdong/tf_examples/test_partition_worker.py:23) ]]
=====================

Errors may have originated from an input operation.
Input Source operations connected to node add_b:
 add_a (defined at /experimental/users/jingdong/tf_examples/test_partition_worker.py:19)
 zeros (defined at /experimental/users/jingdong/tf_examples/test_partition_worker.py:22)

PiperOrigin-RevId: 242999872